# Generated by Django 4.2.7 on 2024-11-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Имя")),
                ("descriptions", models.TextField(verbose_name="Описание")),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создание"
                    ),
                ),
                ("photo", models.ImageField(upload_to="product", verbose_name="Фото")),
            ],
            options={
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="base.product",
                verbose_name="Продукт",
            ),
            preserve_default=False,
        ),
    ]
