# Generated by Django 4.2.7 on 2024-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_remove_order_product_orderproduct_order_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderproduct",
            options={"verbose_name_plural": "Заказанные продукты"},
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="base.OrderProduct", to="base.product", verbose_name="Продукты"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("completed", "Завершён"),
                    ("order_processing", "Обработка заказа"),
                    ("assigning_courier", "Назначаем курьера"),
                    ("courier_on_way", "Курьер в пути"),
                    ("order_shipped", "Отгрузка заказа"),
                    ("order_received", "Заказ получен"),
                    ("order_canceled", "Заказ отменён"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
