# Generated by Django 4.2.7 on 2024-11-23 00:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_order_options_alter_orderproduct_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.DeleteModel(
            name="OrderProduct",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
