# Generated by Django 4.2.7 on 2024-11-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_remove_order_products_delete_orderproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.CharField(default=1, max_length=155, verbose_name="Цена"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.CharField(
                default=1, max_length=20, verbose_name="Количество товара"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="title",
            field=models.CharField(default=1, max_length=155, verbose_name="Заголовка"),
            preserve_default=False,
        ),
    ]
