# Generated by Django 4.2.7 on 2024-11-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_remove_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(verbose_name="Количество товара"),
        ),
    ]
