# Generated by Django 4.2.7 on 2024-11-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_alter_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
    ]
