# Generated by Django 4.2.7 on 2024-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type_user",
            field=models.CharField(
                blank=True,
                choices=[("Клиент", "Клиент"), ("Курьер", "Курьер")],
                default="Клиент",
                max_length=50,
                null=True,
                verbose_name="Тип пользователя",
            ),
        ),
    ]
