# Generated by Django 4.2.7 on 2024-11-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_type_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=155, verbose_name="ФИО")),
                (
                    "phone_number",
                    models.CharField(max_length=25, verbose_name="Номер Телефона"),
                ),
                ("about_me", models.TextField(verbose_name="О себе")),
                (
                    "photo1",
                    models.ImageField(
                        upload_to="Kura",
                        verbose_name="Загрузите первую сторону паспорта",
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        upload_to="Kura",
                        verbose_name="Загрузите вторую сторону паспорта",
                    ),
                ),
                ("age", models.CharField(max_length=25, verbose_name="Возраст")),
            ],
            options={
                "verbose_name_plural": "Как стать курой",
            },
        ),
    ]
