# Generated by Django 4.2.7 on 2024-11-22 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0003_remove_order_product_orderproduct_order_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название транспортного средства"
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номерной знак"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Вместимость (в кг)"),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Транспортное средство",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_location",
                    models.CharField(max_length=255, verbose_name="Начальная точка"),
                ),
                (
                    "end_location",
                    models.CharField(max_length=255, verbose_name="Конечная точка"),
                ),
                ("distance", models.FloatField(verbose_name="Дистанция (в км)")),
                (
                    "estimated_time",
                    models.DurationField(verbose_name="Ожидаемое время доставки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания маршрута"
                    ),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Курьер",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planning.vehicle",
                        verbose_name="Транспортное средство",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Маршрут",
            },
        ),
    ]
