# Generated by Django 4.2.7 on 2024-11-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("in_progress", "В пути"),
                    ("completed", "Завершён"),
                    ("cancelled", "Отменён"),
                ],
                default=1,
                max_length=50,
                verbose_name="Статус",
            ),
            preserve_default=False,
        ),
    ]
